FROM node:20-alpine AS base

# Install dependencies
FROM base AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on preferred package manager
COPY package.json package-lock.json* ./

RUN npm install

# COPY THE REST OF THE SOURCE CODE
COPY . .

# Build
RUN npm run dev

EXPOSE 3000